version: '3'

services:
  api:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: yarn dev
    environment:
        NODE_ENV: development
        PORT: 3000
        LOG_LEVEL: 'debug'
        MYSQL_HOST: ""
        MYSQL_USER: ""
        MYSQL_PASSWORD: ""
        MYSQL_DATABASE: ""
        PLAID_CLIENT_ID: ""
        PLAID_PUBLIC_KEY: ""
        PLAID_SECRET: ""
        PLAID_ENV: "https://sandbox.plaid.com"
